from mrep import mrep

def test_smgb():
	seq = 'TAGAGATAGAATGGGTCCAGAGTTTTGTAATTTCCATGGGTCCAGAGTTTTGTAATTTATTATATAGAGATAGAATGGGTCCAGAGTTTTGTAATTTCCATGGGTCCAGAGTTTTGTAATTTAT'
	out = mrep(seq)
	set_out = set(out)
	assert 'TAGAGATAGAATGGGTCCAGAGTTTTGTAATTTCCATGGGTCCAGAGTTTTGTAATTTAT' in set_out
	assert 'ATGGGTCCAGAGTTTTGTAATTT' in set_out
